name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.6  

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      # Étape 4 : Générer les fichiers HTML
      - name: Generate HTML files
        run: python script.py

      # Étape 5 : Vérifier les fichiers HTML
      - name: Test HTML files
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -e wwwroot/*.html || exit 1

      # Étape 6 : Démarrer un serveur web temporaire
      - name: Start temporary web server
        run: |
          python3 -m http.server 5500 &
          sleep 3
        working-directory: ./wwwroot 

      # Étape 7 : Test de fumée avec curl
      - name: Smoke Test
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -I http://127.0.0.1:5500 || exit 1

      # Étape 8 : Tests fonctionnels avec Playwright
      - name: Run functional tests
        run: |
          pytest tests/test_functional.py

      # Étape 9 : Déployer les fichiers générés (si besoin)
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wwwroot
          destination_branch: gh-pages
